# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0038_auto_20160419_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatline',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, verbose_name='ID', primary_key=True)),
                ('fgm', models.PositiveIntegerField(default=0)),
                ('fga', models.PositiveIntegerField(default=0)),
                ('threepm', models.PositiveIntegerField(default=0)),
                ('threepa', models.PositiveIntegerField(default=0)),
                ('dreb', models.PositiveIntegerField(default=0)),
                ('oreb', models.PositiveIntegerField(default=0)),
                ('total_rebounds', models.PositiveIntegerField(default=0)),
                ('asts', models.PositiveIntegerField(default=0)),
                ('pot_ast', models.PositiveIntegerField(default=0)),
                ('blk', models.PositiveIntegerField(default=0)),
                ('ba', models.PositiveIntegerField(default=0)),
                ('stls', models.PositiveIntegerField(default=0)),
                ('to', models.PositiveIntegerField(default=0)),
                ('fd', models.PositiveIntegerField(default=0)),
                ('pf', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('ast_points', models.PositiveIntegerField(default=0)),
                ('def_pos', models.PositiveIntegerField(default=0)),
                ('off_pos', models.PositiveIntegerField(default=0)),
                ('total_pos', models.PositiveIntegerField(default=0)),
                ('dreb_opp', models.PositiveIntegerField(default=0)),
                ('oreb_opp', models.PositiveIntegerField(default=0)),
                ('ast_fgm', models.PositiveIntegerField(default=0)),
                ('ast_fga', models.PositiveIntegerField(default=0)),
                ('unast_fgm', models.PositiveIntegerField(default=0)),
                ('unast_fga', models.PositiveIntegerField(default=0)),
                ('pga', models.PositiveIntegerField(default=0)),
                ('pgm', models.PositiveIntegerField(default=0)),
                ('fastbreaks', models.PositiveIntegerField(default=0)),
                ('fastbreak_points', models.PositiveIntegerField(default=0)),
                ('second_chance_points', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('game_type', models.CharField(choices=[('5v5', '5on5'), ('4v4', '4on4'), ('3v3', '3on3'), ('2v2', '2on2'), ('1v1', '1on1')], max_length=30)),
                ('player', models.ForeignKey(on_delete=models.CASCADE, to='basketball.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonStatline',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, verbose_name='ID', primary_key=True)),
                ('fgm', models.PositiveIntegerField(default=0)),
                ('fga', models.PositiveIntegerField(default=0)),
                ('threepm', models.PositiveIntegerField(default=0)),
                ('threepa', models.PositiveIntegerField(default=0)),
                ('dreb', models.PositiveIntegerField(default=0)),
                ('oreb', models.PositiveIntegerField(default=0)),
                ('total_rebounds', models.PositiveIntegerField(default=0)),
                ('asts', models.PositiveIntegerField(default=0)),
                ('pot_ast', models.PositiveIntegerField(default=0)),
                ('blk', models.PositiveIntegerField(default=0)),
                ('ba', models.PositiveIntegerField(default=0)),
                ('stls', models.PositiveIntegerField(default=0)),
                ('to', models.PositiveIntegerField(default=0)),
                ('fd', models.PositiveIntegerField(default=0)),
                ('pf', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('ast_points', models.PositiveIntegerField(default=0)),
                ('def_pos', models.PositiveIntegerField(default=0)),
                ('off_pos', models.PositiveIntegerField(default=0)),
                ('total_pos', models.PositiveIntegerField(default=0)),
                ('dreb_opp', models.PositiveIntegerField(default=0)),
                ('oreb_opp', models.PositiveIntegerField(default=0)),
                ('ast_fgm', models.PositiveIntegerField(default=0)),
                ('ast_fga', models.PositiveIntegerField(default=0)),
                ('unast_fgm', models.PositiveIntegerField(default=0)),
                ('unast_fga', models.PositiveIntegerField(default=0)),
                ('pga', models.PositiveIntegerField(default=0)),
                ('pgm', models.PositiveIntegerField(default=0)),
                ('fastbreaks', models.PositiveIntegerField(default=0)),
                ('fastbreak_points', models.PositiveIntegerField(default=0)),
                ('second_chance_points', models.PositiveIntegerField(default=0)),
                ('game_type', models.CharField(choices=[('5v5', '5on5'), ('4v4', '4on4'), ('3v3', '3on3'), ('2v2', '2on2'), ('1v1', '1on1')], max_length=30)),
                ('player', models.ForeignKey(on_delete=models.CASCADE, to='basketball.Player')),
                ('season', models.ForeignKey(on_delete=models.CASCADE, to='basketball.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
