# Generated by Django 2.0 on 2019-05-29 01:55

import basketball.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_memberinvite_player'),
        ('basketball', '0065_auto_20180722_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Group')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image_src', models.ImageField(blank=True, null=True, upload_to=basketball.models.get_team_upload_path)),
                ('is_active', models.BooleanField(help_text='Hides teams from ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Group')),
                ('players', models.ManyToManyField(to='basketball.Player')),
            ],
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_starters',
            field=models.ManyToManyField(blank=True, related_name='away_starter_set', to='basketball.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_starters',
            field=models.ManyToManyField(blank=True, related_name='home_starter_set', to='basketball.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball.Season'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team1',
            field=models.ManyToManyField(blank=True, related_name='team1_set', to='basketball.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team2',
            field=models.ManyToManyField(blank=True, related_name='team2_set', to='basketball.Player'),
        ),
        migrations.AddField(
            model_name='standing',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Team'),
        ),
        migrations.AddField(
            model_name='dailystatline',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_set', to='basketball.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_set', to='basketball.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='losing_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_lost_set', to='basketball.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_won_set', to='basketball.Team'),
        ),
        migrations.AddField(
            model_name='recordstatline',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball.Team'),
        ),
        migrations.AddField(
            model_name='seasonstatline',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball.Team'),
        ),
        migrations.AddField(
            model_name='statline',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball.Team'),
        ),
    ]
