# Generated by Django 2.0 on 2019-05-29 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_memberinvite_player'),
        ('basketball', '0066_auto_20190528_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Group'),
        ),
    ]
