# Generated by Django 2.0 on 2019-05-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_memberinvite_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='league',
            field=models.BooleanField(default=True, help_text='Is this group a league?'),
        ),
    ]
