# Generated by Django 2.0 on 2019-05-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_group_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='league',
            field=models.BooleanField(default=False, help_text='Is this group a league? This cannot be changed afterwards.'),
        ),
    ]
